import React from "react";


// CreateContext basically hamara global context hai jisk andr hum apny saray data ko wrap krdety hain
// ye 1 provider ki trhan behave krta hai....wrapper b keh skyt hain isk andr hmny sary app.jsx k data ko wrap krna hota hai...
// tu osklye hmy 1 or filke banannni prygi jsx k nam sy ...



// Hum log props drilling sy bachny klye contextAPI ka use krty hain...
// Yaani hum data ko app.jsx sy file A , file B m ni bejna chahty direct hum fileC mai behna chahhty hain tu osklye hum 1 global variable bana k osko 3rd file m pass krskty hain lkin osko koo b update ya kuch krdy tu sara data khrab
// so osklye ye contextapi ka concept ata hai...

// Isk three ways hoty hain...
// 1--- CreateContext
//2----Provide 
//3---Consume...



// Is file mai meny crrate kea hai tu it will be called Way 01...
// Way 01....
const UserContext = React.createContext()

export default UserContext;